In [1]:
import torch.nn as nn
import numpy as np
import torch
import torch.optim as optim
from torch.optim.optimizer import Optimizer

In [2]:
class NeuralNet(nn.Module):
    
    def __init__(self):
        super(NeuralNet,self).__init__()
        self.i=nn.Linear(2,5)
        self.l=nn.Linear(5,10)
        self.l1=nn.Linear(10,1)
        
        
    def forward(self,x):
        return self.l1(self.l(self.i(x)))
    

In [3]:
model=NeuralNet()
out=model.forward(torch.rand(1,2))

In [4]:
traindata=torch.load(r'C:\Users\Aushim\Google Drive\' GoodNotes\18667 Algorithms For Large Scale distributed ML\HW3\18667HW3\HW3-prob6\traindata')
test_loader= torch.load(r'C:\Users\Aushim\Google Drive\' GoodNotes\18667 Algorithms For Large Scale distributed ML\HW3\18667HW3\HW3-prob6\test_loader')
dataratios= torch.load(r'C:\Users\Aushim\Google Drive\' GoodNotes\18667 Algorithms For Large Scale distributed ML\HW3\18667HW3\HW3-prob6\dataratios')
partition =torch.load(r'C:\Users\Aushim\Google Drive\' GoodNotes\18667 Algorithms For Large Scale distributed ML\HW3\18667HW3\HW3-prob6\partition')

In [5]:
torch.zeros(5)

tensor([0., 0., 0., 0., 0.])

In [6]:
criterion=nn.Sigmoid()

In [7]:
loss=criterion(out)
loss.backward()

In [8]:
m=model.parameters()
print(m)

<generator object Module.parameters at 0x000002D9017D5D68>


In [9]:
m #generator uses 'yield' after a for loop, which basically returns a value in each for loop. Generators run 1 iteration of the for loop everytime they are called

<generator object Module.parameters at 0x000002D9017D5D68>

In [10]:
for i in m:
    print(i)

Parameter containing:
tensor([[-0.0197,  0.4276],
        [-0.3853, -0.0511],
        [-0.4546,  0.3857],
        [-0.0220, -0.6716],
        [ 0.3855,  0.2678]], requires_grad=True)
Parameter containing:
tensor([-0.4125,  0.4195, -0.5047,  0.2852, -0.6187], requires_grad=True)
Parameter containing:
tensor([[-0.3708,  0.0031, -0.3170,  0.2373, -0.0396],
        [ 0.0556,  0.2937,  0.1855, -0.2691,  0.1801],
        [ 0.1217,  0.0841,  0.4051, -0.3729,  0.0954],
        [ 0.3591, -0.0588, -0.2873,  0.1234, -0.2960],
        [-0.3650, -0.1286, -0.2019,  0.1099, -0.1829],
        [-0.2345,  0.2964,  0.2008,  0.1536, -0.3596],
        [-0.0363,  0.0244, -0.0666, -0.2013,  0.3473],
        [ 0.0407,  0.0947, -0.2300, -0.1252,  0.2743],
        [-0.2055, -0.0200, -0.3946, -0.1247,  0.2620],
        [-0.2680, -0.2256, -0.1557,  0.3557,  0.0820]], requires_grad=True)
Parameter containing:
tensor([-0.0174, -0.0418, -0.3103,  0.3874,  0.3733, -0.0120,  0.3958, -0.0426,
        -0.2509, -0.1188],

In [11]:
for i in model.named_parameters():
    print(i.weight) #i,l,l1 are all the layer names defined in the model above

AttributeError: 'tuple' object has no attribute 'weight'

In [12]:
for i in model.named_parameters():
    print(i)

('i.weight', Parameter containing:
tensor([[-0.0197,  0.4276],
        [-0.3853, -0.0511],
        [-0.4546,  0.3857],
        [-0.0220, -0.6716],
        [ 0.3855,  0.2678]], requires_grad=True))
('i.bias', Parameter containing:
tensor([-0.4125,  0.4195, -0.5047,  0.2852, -0.6187], requires_grad=True))
('l.weight', Parameter containing:
tensor([[-0.3708,  0.0031, -0.3170,  0.2373, -0.0396],
        [ 0.0556,  0.2937,  0.1855, -0.2691,  0.1801],
        [ 0.1217,  0.0841,  0.4051, -0.3729,  0.0954],
        [ 0.3591, -0.0588, -0.2873,  0.1234, -0.2960],
        [-0.3650, -0.1286, -0.2019,  0.1099, -0.1829],
        [-0.2345,  0.2964,  0.2008,  0.1536, -0.3596],
        [-0.0363,  0.0244, -0.0666, -0.2013,  0.3473],
        [ 0.0407,  0.0947, -0.2300, -0.1252,  0.2743],
        [-0.2055, -0.0200, -0.3946, -0.1247,  0.2620],
        [-0.2680, -0.2256, -0.1557,  0.3557,  0.0820]], requires_grad=True))
('l.bias', Parameter containing:
tensor([-0.0174, -0.0418, -0.3103,  0.3874,  0.3733, -0

In [13]:
for i in model.named_parameters():
    print(i[0],"and",i[1],'\n\n')

i.weight and Parameter containing:
tensor([[-0.0197,  0.4276],
        [-0.3853, -0.0511],
        [-0.4546,  0.3857],
        [-0.0220, -0.6716],
        [ 0.3855,  0.2678]], requires_grad=True) 


i.bias and Parameter containing:
tensor([-0.4125,  0.4195, -0.5047,  0.2852, -0.6187], requires_grad=True) 


l.weight and Parameter containing:
tensor([[-0.3708,  0.0031, -0.3170,  0.2373, -0.0396],
        [ 0.0556,  0.2937,  0.1855, -0.2691,  0.1801],
        [ 0.1217,  0.0841,  0.4051, -0.3729,  0.0954],
        [ 0.3591, -0.0588, -0.2873,  0.1234, -0.2960],
        [-0.3650, -0.1286, -0.2019,  0.1099, -0.1829],
        [-0.2345,  0.2964,  0.2008,  0.1536, -0.3596],
        [-0.0363,  0.0244, -0.0666, -0.2013,  0.3473],
        [ 0.0407,  0.0947, -0.2300, -0.1252,  0.2743],
        [-0.2055, -0.0200, -0.3946, -0.1247,  0.2620],
        [-0.2680, -0.2256, -0.1557,  0.3557,  0.0820]], requires_grad=True) 


l.bias and Parameter containing:
tensor([-0.0174, -0.0418, -0.3103,  0.3874,  0.37

In [14]:
print(loss)
print(loss.data, loss.grad, loss.grad_fn)

tensor([[0.4492]], grad_fn=<SigmoidBackward>)
tensor([[0.4492]]) None <SigmoidBackward object at 0x000002D9050E8048>


In [15]:
print(model.l)
print(model.l.bias)
print(type(model.l.bias),model.l.bias,model.l.bias.grad)


Linear(in_features=5, out_features=10, bias=True)
Parameter containing:
tensor([-0.0174, -0.0418, -0.3103,  0.3874,  0.3733, -0.0120,  0.3958, -0.0426,
        -0.2509, -0.1188], requires_grad=True)
<class 'torch.nn.parameter.Parameter'> Parameter containing:
tensor([-0.0174, -0.0418, -0.3103,  0.3874,  0.3733, -0.0120,  0.3958, -0.0426,
        -0.2509, -0.1188], requires_grad=True) tensor([ 0.0157,  0.0550, -0.0350,  0.0252, -0.0299,  0.0118, -0.0676, -0.0446,
         0.0533, -0.0154])


In [16]:
model.l.weight.grad

tensor([[-2.6969e-03,  6.6572e-05, -1.1340e-02, -2.2752e-03, -1.1192e-03],
        [-9.4555e-03,  2.3341e-04, -3.9760e-02, -7.9769e-03, -3.9241e-03],
        [ 6.0279e-03, -1.4880e-04,  2.5347e-02,  5.0853e-03,  2.5016e-03],
        [-4.3288e-03,  1.0686e-04, -1.8203e-02, -3.6519e-03, -1.7965e-03],
        [ 5.1392e-03, -1.2686e-04,  2.1610e-02,  4.3355e-03,  2.1328e-03],
        [-2.0287e-03,  5.0080e-05, -8.5308e-03, -1.7115e-03, -8.4194e-04],
        [ 1.1638e-02, -2.8729e-04,  4.8938e-02,  9.8183e-03,  4.8299e-03],
        [ 7.6701e-03, -1.8934e-04,  3.2252e-02,  6.4707e-03,  3.1831e-03],
        [-9.1694e-03,  2.2635e-04, -3.8557e-02, -7.7356e-03, -3.8053e-03],
        [ 2.6420e-03, -6.5218e-05,  1.1110e-02,  2.2289e-03,  1.0965e-03]])

In [17]:
optimizer=optim.SGD(model.parameters(),lr=1)  #Uses the grad computed in backward() to update the weights using some optimization and lr

In [18]:
optimizer.step() #step actually computes the x_t+1 from x_t, grad and lr

In [19]:
model.l.weight.grad

tensor([[-2.6969e-03,  6.6572e-05, -1.1340e-02, -2.2752e-03, -1.1192e-03],
        [-9.4555e-03,  2.3341e-04, -3.9760e-02, -7.9769e-03, -3.9241e-03],
        [ 6.0279e-03, -1.4880e-04,  2.5347e-02,  5.0853e-03,  2.5016e-03],
        [-4.3288e-03,  1.0686e-04, -1.8203e-02, -3.6519e-03, -1.7965e-03],
        [ 5.1392e-03, -1.2686e-04,  2.1610e-02,  4.3355e-03,  2.1328e-03],
        [-2.0287e-03,  5.0080e-05, -8.5308e-03, -1.7115e-03, -8.4194e-04],
        [ 1.1638e-02, -2.8729e-04,  4.8938e-02,  9.8183e-03,  4.8299e-03],
        [ 7.6701e-03, -1.8934e-04,  3.2252e-02,  6.4707e-03,  3.1831e-03],
        [-9.1694e-03,  2.2635e-04, -3.8557e-02, -7.7356e-03, -3.8053e-03],
        [ 2.6420e-03, -6.5218e-05,  1.1110e-02,  2.2289e-03,  1.0965e-03]])

In [20]:
model.l.weight

Parameter containing:
tensor([[-0.3681,  0.0030, -0.3057,  0.2396, -0.0384],
        [ 0.0650,  0.2935,  0.2253, -0.2612,  0.1840],
        [ 0.1157,  0.0843,  0.3798, -0.3780,  0.0929],
        [ 0.3634, -0.0589, -0.2691,  0.1271, -0.2942],
        [-0.3702, -0.1285, -0.2235,  0.1056, -0.1851],
        [-0.2325,  0.2964,  0.2094,  0.1553, -0.3588],
        [-0.0479,  0.0247, -0.1155, -0.2111,  0.3425],
        [ 0.0330,  0.0949, -0.2623, -0.1317,  0.2711],
        [-0.1963, -0.0203, -0.3560, -0.1169,  0.2658],
        [-0.2707, -0.2255, -0.1668,  0.3534,  0.0809]], requires_grad=True)

In [21]:
optimizer.param_groups  #param_groups is a list of dict. Each dict element of the list contains the hyperparameters used to update the weights in the next round. It is a list because a model can have more than one set of optimizers for diff circumstances (read more about this idk). Accessed by optimizer.param_groups[0]['lr'] or optimizer.param_groups[0]['params']

[{'params': [Parameter containing:
   tensor([[-0.0236,  0.4252],
           [-0.4008, -0.0606],
           [-0.4430,  0.3929],
           [-0.0327, -0.6781],
           [ 0.4088,  0.2820]], requires_grad=True), Parameter containing:
   tensor([-0.4164,  0.4039, -0.4930,  0.2744, -0.5954], requires_grad=True), Parameter containing:
   tensor([[-0.3681,  0.0030, -0.3057,  0.2396, -0.0384],
           [ 0.0650,  0.2935,  0.2253, -0.2612,  0.1840],
           [ 0.1157,  0.0843,  0.3798, -0.3780,  0.0929],
           [ 0.3634, -0.0589, -0.2691,  0.1271, -0.2942],
           [-0.3702, -0.1285, -0.2235,  0.1056, -0.1851],
           [-0.2325,  0.2964,  0.2094,  0.1553, -0.3588],
           [-0.0479,  0.0247, -0.1155, -0.2111,  0.3425],
           [ 0.0330,  0.0949, -0.2623, -0.1317,  0.2711],
           [-0.1963, -0.0203, -0.3560, -0.1169,  0.2658],
           [-0.2707, -0.2255, -0.1668,  0.3534,  0.0809]], requires_grad=True), Parameter containing:
   tensor([-0.0331, -0.0968, -0.2753,  0.3

In [22]:
model.param_groups

AttributeError: 'NeuralNet' object has no attribute 'param_groups'

In [23]:
optimizer.param_groups[0]['params']

[Parameter containing:
 tensor([[-0.0236,  0.4252],
         [-0.4008, -0.0606],
         [-0.4430,  0.3929],
         [-0.0327, -0.6781],
         [ 0.4088,  0.2820]], requires_grad=True), Parameter containing:
 tensor([-0.4164,  0.4039, -0.4930,  0.2744, -0.5954], requires_grad=True), Parameter containing:
 tensor([[-0.3681,  0.0030, -0.3057,  0.2396, -0.0384],
         [ 0.0650,  0.2935,  0.2253, -0.2612,  0.1840],
         [ 0.1157,  0.0843,  0.3798, -0.3780,  0.0929],
         [ 0.3634, -0.0589, -0.2691,  0.1271, -0.2942],
         [-0.3702, -0.1285, -0.2235,  0.1056, -0.1851],
         [-0.2325,  0.2964,  0.2094,  0.1553, -0.3588],
         [-0.0479,  0.0247, -0.1155, -0.2111,  0.3425],
         [ 0.0330,  0.0949, -0.2623, -0.1317,  0.2711],
         [-0.1963, -0.0203, -0.3560, -0.1169,  0.2658],
         [-0.2707, -0.2255, -0.1668,  0.3534,  0.0809]], requires_grad=True), Parameter containing:
 tensor([-0.0331, -0.0968, -0.2753,  0.3622,  0.4031, -0.0238,  0.4634,  0.0020,
     

In [24]:
for group in optimizer.param_groups:
    #print(group['lr'])
    for i, p in enumerate(group['params']):
        y=torch.ones(p.data.shape)
        #p.data.add_(1,y)
        print(p)
        print('s')

Parameter containing:
tensor([[-0.0236,  0.4252],
        [-0.4008, -0.0606],
        [-0.4430,  0.3929],
        [-0.0327, -0.6781],
        [ 0.4088,  0.2820]], requires_grad=True)
s
Parameter containing:
tensor([-0.4164,  0.4039, -0.4930,  0.2744, -0.5954], requires_grad=True)
s
Parameter containing:
tensor([[-0.3681,  0.0030, -0.3057,  0.2396, -0.0384],
        [ 0.0650,  0.2935,  0.2253, -0.2612,  0.1840],
        [ 0.1157,  0.0843,  0.3798, -0.3780,  0.0929],
        [ 0.3634, -0.0589, -0.2691,  0.1271, -0.2942],
        [-0.3702, -0.1285, -0.2235,  0.1056, -0.1851],
        [-0.2325,  0.2964,  0.2094,  0.1553, -0.3588],
        [-0.0479,  0.0247, -0.1155, -0.2111,  0.3425],
        [ 0.0330,  0.0949, -0.2623, -0.1317,  0.2711],
        [-0.1963, -0.0203, -0.3560, -0.1169,  0.2658],
        [-0.2707, -0.2255, -0.1668,  0.3534,  0.0809]], requires_grad=True)
s
Parameter containing:
tensor([-0.0331, -0.0968, -0.2753,  0.3622,  0.4031, -0.0238,  0.4634,  0.0020,
        -0.3042, -0.

In [25]:
tensor_params=[]
x=model.parameters()
for i,j in enumerate(x):
    tensor_params.append(j.data)

print(tensor_params)

[tensor([[-0.0236,  0.4252],
        [-0.4008, -0.0606],
        [-0.4430,  0.3929],
        [-0.0327, -0.6781],
        [ 0.4088,  0.2820]]), tensor([-0.4164,  0.4039, -0.4930,  0.2744, -0.5954]), tensor([[-0.3681,  0.0030, -0.3057,  0.2396, -0.0384],
        [ 0.0650,  0.2935,  0.2253, -0.2612,  0.1840],
        [ 0.1157,  0.0843,  0.3798, -0.3780,  0.0929],
        [ 0.3634, -0.0589, -0.2691,  0.1271, -0.2942],
        [-0.3702, -0.1285, -0.2235,  0.1056, -0.1851],
        [-0.2325,  0.2964,  0.2094,  0.1553, -0.3588],
        [-0.0479,  0.0247, -0.1155, -0.2111,  0.3425],
        [ 0.0330,  0.0949, -0.2623, -0.1317,  0.2711],
        [-0.1963, -0.0203, -0.3560, -0.1169,  0.2658],
        [-0.2707, -0.2255, -0.1668,  0.3534,  0.0809]]), tensor([-0.0331, -0.0968, -0.2753,  0.3622,  0.4031, -0.0238,  0.4634,  0.0020,
        -0.3042, -0.1035]), tensor([[ 0.0030,  0.2612,  0.0011, -0.0310, -0.2639,  0.0755, -0.3859, -0.2088,
          0.1983, -0.0575]]), tensor([-0.3637])]


In [ ]:
#testing state dict

In [26]:
model.state_dict()

OrderedDict([('i.weight', tensor([[-0.0236,  0.4252],
                      [-0.4008, -0.0606],
                      [-0.4430,  0.3929],
                      [-0.0327, -0.6781],
                      [ 0.4088,  0.2820]])),
             ('i.bias', tensor([-0.4164,  0.4039, -0.4930,  0.2744, -0.5954])),
             ('l.weight',
              tensor([[-0.3681,  0.0030, -0.3057,  0.2396, -0.0384],
                      [ 0.0650,  0.2935,  0.2253, -0.2612,  0.1840],
                      [ 0.1157,  0.0843,  0.3798, -0.3780,  0.0929],
                      [ 0.3634, -0.0589, -0.2691,  0.1271, -0.2942],
                      [-0.3702, -0.1285, -0.2235,  0.1056, -0.1851],
                      [-0.2325,  0.2964,  0.2094,  0.1553, -0.3588],
                      [-0.0479,  0.0247, -0.1155, -0.2111,  0.3425],
                      [ 0.0330,  0.0949, -0.2623, -0.1317,  0.2711],
                      [-0.1963, -0.0203, -0.3560, -0.1169,  0.2658],
                      [-0.2707, -0.2255, -0.1668

In [27]:
#Adding model weights to themselves using state_dict

print("Model's state_dict:")
sd=model.state_dict()
for param_tensor in sd:
    print(param_tensor, "\t", sd[param_tensor].size(),"\n the weights are:", sd[param_tensor],"\n")
    sd[param_tensor]+=sd[param_tensor]


Model's state_dict:
i.weight 	 torch.Size([5, 2]) 
 the weights are: tensor([[-0.0236,  0.4252],
        [-0.4008, -0.0606],
        [-0.4430,  0.3929],
        [-0.0327, -0.6781],
        [ 0.4088,  0.2820]]) 

i.bias 	 torch.Size([5]) 
 the weights are: tensor([-0.4164,  0.4039, -0.4930,  0.2744, -0.5954]) 

l.weight 	 torch.Size([10, 5]) 
 the weights are: tensor([[-0.3681,  0.0030, -0.3057,  0.2396, -0.0384],
        [ 0.0650,  0.2935,  0.2253, -0.2612,  0.1840],
        [ 0.1157,  0.0843,  0.3798, -0.3780,  0.0929],
        [ 0.3634, -0.0589, -0.2691,  0.1271, -0.2942],
        [-0.3702, -0.1285, -0.2235,  0.1056, -0.1851],
        [-0.2325,  0.2964,  0.2094,  0.1553, -0.3588],
        [-0.0479,  0.0247, -0.1155, -0.2111,  0.3425],
        [ 0.0330,  0.0949, -0.2623, -0.1317,  0.2711],
        [-0.1963, -0.0203, -0.3560, -0.1169,  0.2658],
        [-0.2707, -0.2255, -0.1668,  0.3534,  0.0809]]) 

l.bias 	 torch.Size([10]) 
 the weights are: tensor([-0.0331, -0.0968, -0.2753,  0.36

In [28]:
model.load_state_dict(sd)

<All keys matched successfully>

In [29]:
model.state_dict()

OrderedDict([('i.weight', tensor([[-0.0472,  0.8504],
                      [-0.8017, -0.1212],
                      [-0.8859,  0.7857],
                      [-0.0653, -1.3563],
                      [ 0.8175,  0.5640]])),
             ('i.bias', tensor([-0.8328,  0.8078, -0.9860,  0.5489, -1.1909])),
             ('l.weight',
              tensor([[-0.7362,  0.0060, -0.6114,  0.4792, -0.0769],
                      [ 0.1301,  0.5870,  0.4505, -0.5223,  0.3680],
                      [ 0.2314,  0.1685,  0.7595, -0.7560,  0.1859],
                      [ 0.7268, -0.1178, -0.5383,  0.2542, -0.5884],
                      [-0.7404, -0.2570, -0.4471,  0.2112, -0.3701],
                      [-0.4649,  0.5927,  0.4187,  0.3106, -0.7176],
                      [-0.0958,  0.0493, -0.2311, -0.4222,  0.6849],
                      [ 0.0660,  0.1898, -0.5246, -0.2633,  0.5423],
                      [-0.3926, -0.0405, -0.7121, -0.2339,  0.5317],
                      [-0.5414, -0.4511, -0.3335

In [30]:
optimizer.state_dict()

{'state': {},
 'param_groups': [{'lr': 1,
   'momentum': 0,
   'dampening': 0,
   'weight_decay': 0,
   'nesterov': False,
   'params': [3133038966176,
    3131056412208,
    3131056412280,
    3131056412352,
    3131056412424,
    3131056412496]}]}

In [31]:
optimizer.state_dict()['param_groups'][0]['params'][0]

3133038966176

In [32]:
optimizer.param_groups #note this has different parameters from the params in state_dict. Are the values of params in state_dict just pointers?

[{'params': [Parameter containing:
   tensor([[-0.0472,  0.8504],
           [-0.8017, -0.1212],
           [-0.8859,  0.7857],
           [-0.0653, -1.3563],
           [ 0.8175,  0.5640]], requires_grad=True), Parameter containing:
   tensor([-0.8328,  0.8078, -0.9860,  0.5489, -1.1909], requires_grad=True), Parameter containing:
   tensor([[-0.7362,  0.0060, -0.6114,  0.4792, -0.0769],
           [ 0.1301,  0.5870,  0.4505, -0.5223,  0.3680],
           [ 0.2314,  0.1685,  0.7595, -0.7560,  0.1859],
           [ 0.7268, -0.1178, -0.5383,  0.2542, -0.5884],
           [-0.7404, -0.2570, -0.4471,  0.2112, -0.3701],
           [-0.4649,  0.5927,  0.4187,  0.3106, -0.7176],
           [-0.0958,  0.0493, -0.2311, -0.4222,  0.6849],
           [ 0.0660,  0.1898, -0.5246, -0.2633,  0.5423],
           [-0.3926, -0.0405, -0.7121, -0.2339,  0.5317],
           [-0.5414, -0.4511, -0.3335,  0.7069,  0.1618]], requires_grad=True), Parameter containing:
   tensor([-0.0662, -0.1935, -0.5506,  0.7

In [33]:
#Will weights updated in model reflect in optimizer?

optimizer.param_groups[0]['params'][0] #.data gives just the tensor. The tensor data has updated to the new weights set in model

Parameter containing:
tensor([[-0.0472,  0.8504],
        [-0.8017, -0.1212],
        [-0.8859,  0.7857],
        [-0.0653, -1.3563],
        [ 0.8175,  0.5640]], requires_grad=True)

In [34]:
optimizer.param_groups[0]['params'][0].grad.data #there is no grad initially, until forward and back are called

tensor([[ 0.0039,  0.0024],
        [ 0.0156,  0.0095],
        [-0.0116, -0.0071],
        [ 0.0107,  0.0065],
        [-0.0232, -0.0142]])

In [35]:
#Will weights updated in optimizer reflect in model?
optimizer.param_groups[0]['params'][0].data+=1

In [36]:
optimizer.param_groups[0]['params'][0]

Parameter containing:
tensor([[ 0.9528,  1.8504],
        [ 0.1983,  0.8788],
        [ 0.1141,  1.7857],
        [ 0.9347, -0.3563],
        [ 1.8175,  1.5640]], requires_grad=True)

In [37]:
model.state_dict()  #see that the first model weights have updated

OrderedDict([('i.weight', tensor([[ 0.9528,  1.8504],
                      [ 0.1983,  0.8788],
                      [ 0.1141,  1.7857],
                      [ 0.9347, -0.3563],
                      [ 1.8175,  1.5640]])),
             ('i.bias', tensor([-0.8328,  0.8078, -0.9860,  0.5489, -1.1909])),
             ('l.weight',
              tensor([[-0.7362,  0.0060, -0.6114,  0.4792, -0.0769],
                      [ 0.1301,  0.5870,  0.4505, -0.5223,  0.3680],
                      [ 0.2314,  0.1685,  0.7595, -0.7560,  0.1859],
                      [ 0.7268, -0.1178, -0.5383,  0.2542, -0.5884],
                      [-0.7404, -0.2570, -0.4471,  0.2112, -0.3701],
                      [-0.4649,  0.5927,  0.4187,  0.3106, -0.7176],
                      [-0.0958,  0.0493, -0.2311, -0.4222,  0.6849],
                      [ 0.0660,  0.1898, -0.5246, -0.2633,  0.5423],
                      [-0.3926, -0.0405, -0.7121, -0.2339,  0.5317],
                      [-0.5414, -0.4511, -0.3335

In [ ]:
#Named Parameters Testing

In [38]:
model.named_parameters

<bound method Module.named_parameters of NeuralNet(
  (i): Linear(in_features=2, out_features=5, bias=True)
  (l): Linear(in_features=5, out_features=10, bias=True)
  (l1): Linear(in_features=10, out_features=1, bias=True)
)>

In [40]:
model.named_parameters()

<generator object Module.named_parameters at 0x000002D9053989A8>

In [41]:
dict(model.named_parameters())

{'i.weight': Parameter containing:
 tensor([[ 0.9528,  1.8504],
         [ 0.1983,  0.8788],
         [ 0.1141,  1.7857],
         [ 0.9347, -0.3563],
         [ 1.8175,  1.5640]], requires_grad=True),
 'i.bias': Parameter containing:
 tensor([-0.8328,  0.8078, -0.9860,  0.5489, -1.1909], requires_grad=True),
 'l.weight': Parameter containing:
 tensor([[-0.7362,  0.0060, -0.6114,  0.4792, -0.0769],
         [ 0.1301,  0.5870,  0.4505, -0.5223,  0.3680],
         [ 0.2314,  0.1685,  0.7595, -0.7560,  0.1859],
         [ 0.7268, -0.1178, -0.5383,  0.2542, -0.5884],
         [-0.7404, -0.2570, -0.4471,  0.2112, -0.3701],
         [-0.4649,  0.5927,  0.4187,  0.3106, -0.7176],
         [-0.0958,  0.0493, -0.2311, -0.4222,  0.6849],
         [ 0.0660,  0.1898, -0.5246, -0.2633,  0.5423],
         [-0.3926, -0.0405, -0.7121, -0.2339,  0.5317],
         [-0.5414, -0.4511, -0.3335,  0.7069,  0.1618]], requires_grad=True),
 'l.bias': Parameter containing:
 tensor([-0.0662, -0.1935, -0.5506,  0.

In [42]:
#add weights and copy back to model
d=dict(model.named_parameters())
for name,param in model.named_parameters():
    d[name].data.copy_(param+param)

In [43]:
d

{'i.weight': Parameter containing:
 tensor([[ 1.9056,  3.7007],
         [ 0.3966,  1.7576],
         [ 0.2282,  3.5714],
         [ 1.8694, -0.7126],
         [ 3.6351,  3.1281]], requires_grad=True),
 'i.bias': Parameter containing:
 tensor([-1.6656,  1.6156, -1.9721,  1.0977, -2.3817], requires_grad=True),
 'l.weight': Parameter containing:
 tensor([[-1.4725,  0.0119, -1.2227,  0.9584, -0.1538],
         [ 0.2602,  1.1740,  0.9010, -1.0446,  0.7360],
         [ 0.4627,  0.3370,  1.5191, -1.5120,  0.3718],
         [ 1.4536, -0.2356, -1.0765,  0.5083, -1.1769],
         [-1.4808, -0.5141, -0.8942,  0.4225, -0.7403],
         [-0.9298,  1.1854,  0.8375,  0.6212, -1.4352],
         [-0.1916,  0.0987, -0.4621, -0.8445,  1.3699],
         [ 0.1320,  0.3795, -1.0492, -0.5266,  1.0845],
         [-0.7853, -0.0810, -1.4242, -0.4678,  1.0634],
         [-1.0827, -0.9021, -0.6671,  1.4137,  0.3235]], requires_grad=True),
 'l.bias': Parameter containing:
 tensor([-0.1324, -0.3871, -1.1012,  1.

In [44]:
#Now load the dictionary as a state
model.load_state_dict(d)

<All keys matched successfully>

In [45]:
dict(model.named_parameters())

{'i.weight': Parameter containing:
 tensor([[ 1.9056,  3.7007],
         [ 0.3966,  1.7576],
         [ 0.2282,  3.5714],
         [ 1.8694, -0.7126],
         [ 3.6351,  3.1281]], requires_grad=True),
 'i.bias': Parameter containing:
 tensor([-1.6656,  1.6156, -1.9721,  1.0977, -2.3817], requires_grad=True),
 'l.weight': Parameter containing:
 tensor([[-1.4725,  0.0119, -1.2227,  0.9584, -0.1538],
         [ 0.2602,  1.1740,  0.9010, -1.0446,  0.7360],
         [ 0.4627,  0.3370,  1.5191, -1.5120,  0.3718],
         [ 1.4536, -0.2356, -1.0765,  0.5083, -1.1769],
         [-1.4808, -0.5141, -0.8942,  0.4225, -0.7403],
         [-0.9298,  1.1854,  0.8375,  0.6212, -1.4352],
         [-0.1916,  0.0987, -0.4621, -0.8445,  1.3699],
         [ 0.1320,  0.3795, -1.0492, -0.5266,  1.0845],
         [-0.7853, -0.0810, -1.4242, -0.4678,  1.0634],
         [-1.0827, -0.9021, -0.6671,  1.4137,  0.3235]], requires_grad=True),
 'l.bias': Parameter containing:
 tensor([-0.1324, -0.3871, -1.1012,  1.

In [46]:
optimizer.param_groups

[{'params': [Parameter containing:
   tensor([[ 1.9056,  3.7007],
           [ 0.3966,  1.7576],
           [ 0.2282,  3.5714],
           [ 1.8694, -0.7126],
           [ 3.6351,  3.1281]], requires_grad=True), Parameter containing:
   tensor([-1.6656,  1.6156, -1.9721,  1.0977, -2.3817], requires_grad=True), Parameter containing:
   tensor([[-1.4725,  0.0119, -1.2227,  0.9584, -0.1538],
           [ 0.2602,  1.1740,  0.9010, -1.0446,  0.7360],
           [ 0.4627,  0.3370,  1.5191, -1.5120,  0.3718],
           [ 1.4536, -0.2356, -1.0765,  0.5083, -1.1769],
           [-1.4808, -0.5141, -0.8942,  0.4225, -0.7403],
           [-0.9298,  1.1854,  0.8375,  0.6212, -1.4352],
           [-0.1916,  0.0987, -0.4621, -0.8445,  1.3699],
           [ 0.1320,  0.3795, -1.0492, -0.5266,  1.0845],
           [-0.7853, -0.0810, -1.4242, -0.4678,  1.0634],
           [-1.0827, -0.9021, -0.6671,  1.4137,  0.3235]], requires_grad=True), Parameter containing:
   tensor([-0.1324, -0.3871, -1.1012,  1.4

In [ ]:
datapoint_idxs= partition[76]

train_data=np.random.choice(datapoint_idxs,64)



In [ ]:
x_train=[]
y_train=[]

for i in train_data:
    x_train.append(list(traindata[i][0]))
    y_train.append(float(traindata[i][1][0]))
    
x_train=torch.tensor(x_train)
y_train=torch.tensor(y_train)

ta = data_utils.TensorDataset(x_train, y_train)

In [ ]:
import torch.utils.data as data_utils
single_minibatch_loader = data_utils.DataLoader(ta, shuffle=False,batch_size= 1)

In [ ]:
for data in single_minibatch_loader:
    print(data[0].size()[-1])

In [ ]:
optimizer.load_state_dict(optimi.state_dict())

In [ ]:
x=torch.tensor([1,2,3,4])
y=torch.tensor([5,6,7,8])

In [ ]:
y.add_(-1,x)

In [ ]:
y.shape

In [ ]:
y

In [50]:
model.state_dict

<bound method Module.state_dict of NeuralNet(
  (i): Linear(in_features=2, out_features=5, bias=True)
  (l): Linear(in_features=5, out_features=10, bias=True)
  (l1): Linear(in_features=10, out_features=1, bias=True)
)>